[project]
name = "btc-lab"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "lightgbm",
    "scikit-learn",
    "pyarrow",
    "pandas",
    "requests>=2.32.3",
    "huggingface-hub>=0.26.5",
    "websockets>=13.1",
    "numpy>=1.26.4",
]


[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
